# Generated by Django 2.0.7 on 2021-05-03 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('author_firstname', models.CharField(max_length=150)),
                ('author_lastname', models.CharField(max_length=150)),
                ('author_avatar', models.CharField(max_length=150)),
                ('author_bio', models.CharField(max_length=1000, null=True)),
                ('author_profile_picture', models.ImageField(default='authors/default.gif', null=True, upload_to='authors')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('post_title', models.CharField(max_length=150)),
                ('post_date', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Post_Category',
            fields=[
                ('category_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'post_categories',
            },
        ),
        migrations.CreateModel(
            name='Post_Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_number', models.IntegerField(choices=[(1, 'Part 1'), (2, 'Part 2'), (3, 'Part 3'), (4, 'Part 4'), (5, 'Part 5'), (6, 'Part 6'), (7, 'Part 7')])),
                ('heading', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='blog')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='post_categories',
            field=models.ManyToManyField(to='blog.Post_Category'),
        ),
    ]
